### ISSUE TITLE
请教下问题，谢谢！

### ISSUE THREAD

**Issue by luyaninthu** [Maicius/UniversityRecruitment-sSurvey#38]
您好：
同样对这个问题感兴趣，在试着复现看下最后结果时，对相关数据的定义想请教下。
在查看data目录下的文件时。
我对Company_data和Result_data具体的含义不是很清楚？
Ana_company_data和university_data我知道分别是某一年某一个榜单上的公司信息，特定学校的历史招聘会记录，这个理解没问题的吧？

谢谢！！！

**Comment by Maicius** [comment]
company_data是从财富网上爬下来的原始数据，已经经过后放到了ana_company_data，所以company_data已经可以不用管了。Ana_company_data和university_data的理解是正确的
